services:
  - type: web
    name: budget-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: DATABASE_URL
        value: postgresql+psycopg2://postgres:123456@34.133.153.251:5432/expense
      - key: SECRET_KEY
        value: myRandomSecretKey123!
      - key: SESSION_SECRET
        value: myRandomSecretKey123!
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: PLAID_CLIENT_ID
        value: 67a4290da237bf001e5c7ac6
      - key: PLAID_SECRET
        value: 02e5286ff3222322801b1649e99ca5
      - key: PLAID_ENV
        value: sandbox
      - key: PLAID_REDIRECT_URI
        fromService:
          name: budget-ai
          type: web
          property: url
        suffix: /plaid/oauth-callback
      - key: OPENAI_API_KEY
        value: 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