services:
  # A web service
  - type: web
    name: budget-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port --reload main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        # Google Cloud SQL database
        value: postgresql://postgres:CgdvKS7p@34.60.72.203:5432/budget_ai
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: main.py
      - key: PLAID_CLIENT_ID
        value: 67a4290da237bf001e5c7ac6
      - key: PLAID_SECRET
        value: 02e5286ff3222322801b1649e99ca5
      - key: PLAID_ENV
        value: sandbox
      - key: PLAID_REDIRECT_URI
        value: https://budget-ai.onrender.com/plaid/oauth-callback
      - key: OPENAI_API_KEY
        value: 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